'use strict';
const cfg=[{name:'Доходы',title:'Сколько денег приходит?',intro:'Укажи средние суммы за месяц. Если доход нерегулярный, лучше взять осторожную оценку за последние несколько месяцев.',fields:[['salary','Зарплата и постоянный доход'],['extra','Подработка и другие доходы']]},{name:'Расходы',title:'Куда уходят деньги?',intro:'Введи среднемесячные траты без кредитных платежей — их учтём отдельно. Не забудь про нерегулярные расходы, пересчитанные на месяц.',fields:[['housing','Жильё и коммунальные услуги'],['food','Продукты и питание'],['transport','Транспорт'],['family','Семья, здоровье и обязательные траты'],['other','Досуг, покупки и прочее']]},{name:'Долги',title:'Какие есть обязательства?',intro:'Для расчёта нагрузки нужны ежемесячные платежи. Общий остаток долга используется при расчёте чистого капитала.',fields:[['payments','Общие ежемесячные платежи по долгам'],['debt','Остаток всех долгов и кредитов']]},{name:'Капитал',title:'Что уже накоплено?',intro:'Включай доступные денежные резервы и примерную рыночную стоимость других активов. Не учитывай одно и то же дважды.',fields:[['cash','Доступные накопления и резерв'],['assets','Стоимость остальных активов (жильё, инвестиции и другое)']]}];
const fieldHints={salary:'После налогов, сумма на руки.',extra:'Средний доход от подработок за месяц, за вычетом связанных расходов.',housing:'Аренда, коммунальные услуги и содержание жилья — без платежей по ипотеке.',food:'Продукты, кафе и питание за месяц.',transport:'Проезд, топливо, обслуживание транспорта.',family:'Лечение, дети, обязательные покупки и другие необходимые траты.',other:'Необязательные покупки, развлечения и подписки.',payments:'Сумма платежей по ипотеке, кредитам, рассрочкам и займам за месяц.',debt:'Сколько всего осталось вернуть кредиторам, а не первоначальная сумма кредитов.',cash:'Деньги на счетах, вкладах и наличные, которыми реально можно воспользоваться.',assets:'Примерная стоимость жилья, автомобиля, инвестиций и другого имущества. Не дублируй деньги из предыдущего поля.'};const values={};const allFields=cfg.flatMap(s=>s.fields.map(x=>x[0]));allFields.forEach(k=>values[k]=0);let step=0;let pendingReport=null;const cancelPendingReport=()=>{if(pendingReport!==null){clearTimeout(pendingReport);pendingReport=null}};const scheduleReport=()=>{cancelPendingReport();if($('results').classList.contains('show'))pendingReport=setTimeout(()=>{pendingReport=null;results(false)},160)};const $=id=>document.getElementById(id);const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const sum=keys=>keys.reduce((v,k)=>v+(values[k]||0),0);const data=()=>{let income=sum(['salary','extra']),expenses=sum(['housing','food','transport','family','other']),payments=values.payments||0,monthly=expenses+payments,free=income-monthly,essentials=sum(['housing','food','transport','family'])+payments,assets=sum(['cash','assets']),debt=values.debt||0;return {income,expenses,payments,monthly,free,essentials,assets,debt,net:assets-debt,buffer:essentials>0?values.cash/essentials:null,load:income>0?payments/income:null,savings:income>0?free/income:null}};
function render(){const s=cfg[step];$('stepText').textContent=`Этап ${step+1} из 4`;$('tabs').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===step);b.setAttribute('aria-current',i===step?'step':'false')});let fields=s.fields.map(([key,label])=>`<div class="field"><label for="f-${key}">${label}</label><span class="field-hint" id="hint-${key}">${fieldHints[key]||''}</span><div class="inputwrap"><input type="number" id="f-${key}" data-key="${key}" min="0" max="1000000000000" step="any" inputmode="decimal" value="${values[key]||''}" placeholder="0" aria-describedby="hint-${key}" aria-label="${label}"><span class="rub">₽</span></div></div>`).join('');$('stage').innerHTML=`<div class="section"><h3>${s.title}</h3><p>${s.intro}</p><div class="fields">${fields}</div><div class="note">${step===2?'Если долгов нет, оставь поля пустыми. Платежи уже не должны входить в раздел обычных расходов.':step===3?'Важно: стоимость квартиры и других активов не равна свободным деньгам. Для рекомендаций о доступных накоплениях используется отдельное поле «Доступные накопления».':'Не нужно вводить точные личные данные — достаточно приблизительных сумм.'}</div></div>`;$('stage').querySelectorAll('input').forEach(el=>el.addEventListener('input',()=>{const n=el.value===''?0:Number(el.value);if(Number.isFinite(n)&&n>=0&&n<=1e12){values[el.dataset.key]=n;el.removeAttribute('aria-invalid');$('error').textContent='';preview();scheduleReport()}else{el.setAttribute('aria-invalid','true');$('error').textContent='Проверь сумму: допустимы числа от 0 до 1 трлн рублей.';cancelPendingReport();$('results').classList.remove('show')}}));$('prev').disabled=step===0;$('next').textContent=step===3?'Получить результаты →':'Далее →';preview()}
function preview(){const d=data();$('incomePreview').textContent=money(d.income);$('outPreview').textContent=money(d.monthly);$('freePreview').textContent=money(d.free);$('freePreview').className=d.free<0?'red':'green';$('progress').style.width=((step+1)/4*100)+'%';$('progressTrack').setAttribute('aria-valuenow',String(step+1))}
function validate(){for(const [k] of cfg[step].fields){let el=$('f-'+k);if(!el)continue;const n=el.value===''?0:Number(el.value);if(!Number.isFinite(n)||n<0||n>1e12){$('error').textContent='Проверь суммы: допустимы только неотрицательные числа до 1 трлн рублей.';el.setAttribute('aria-invalid','true');el.focus();return false}}return true}
$('prev').onclick=()=>{if(step>0){if(!validate())return;cancelPendingReport();step--;render()}};$('next').onclick=()=>{if(!validate())return;if(step<3){cancelPendingReport();step++;render()}else{cancelPendingReport();results()}};$('tabs').addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t&&validate()){cancelPendingReport();step=Number(t.dataset.tab);render()}});
function calculateScore(d){
 let score=0,weight=0;
 if(d.income>0){score+=clamp(d.free/d.income,0,.25)/.25*30;score+=clamp(1-d.payments/d.income/.5,0,1)*20;weight+=50}
 if(d.essentials>0){score+=clamp(d.buffer||0,0,6)/6*30;weight+=30}
 if(d.assets>0||d.debt>0){score+=(d.net>=0?20:clamp(1+d.net/Math.max(d.debt,1),0,1)*20);weight+=20}
 return weight>0?clamp(Math.round(score/weight*100),0,100):null;
}

function block(title,text){const e=document.createElement('div');e.className='finding';const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=text;e.append(b,p);return e}function add(parent,title,txt){parent.append(block(title,txt))}
function capitalAdvice(d){
 const cash=values.cash||0,other=values.assets||0,free=d.free,base=d.essentials>0?d.essentials*3:0,available=Math.max(0,cash-base);
 const tier=cash<500000?0:cash<2000000?1:cash<5000000?2:cash<20000000?3:4;
 const variants=[
 ['Небольшие суммы: создать запас и проверить идею','Начни с доступного резерва. Если он уже есть, сравни вклад и короткие надёжные облигации с учётом срока и риска. Для малого дела проверь спрос на услугу: ремонт, обучение, дизайн, прокат вещей или помощь бизнесу. Сначала найди потенциальных клиентов и рассчитай расходы, а не покупай оборудование вслепую.'],
 ['От 500 тысяч до 2 миллионов: разделить деньги по задачам','Часть оставь на непредвиденные расходы и ближайшие покупки — на доступном счёте или вкладе. Для денег, которые не понадобятся в ближайшее время, изучи облигации: кто их выпустил, когда вернёт долг и может ли не заплатить. На предпринимательский эксперимент выделяй только ограниченную сумму, потеря которой не нарушит семейный бюджет.'],
 ['От 2 до 5 миллионов: сравнить несколько путей','Первый путь — вклады и качественные облигации с разными сроками погашения, чтобы не зависеть от одной даты. Второй — часть долгосрочных денег вложить в диверсифицированные фонды или акции, понимая, что стоимость может сильно падать. Третий — проверить собственный небольшой бизнес с бюджетом и ограничением убытка. Недвижимость сравнивай по чистому доходу от аренды после ремонта, налогов и простоя, а не только по цене объявления.'],
 ['От 5 до 20 миллионов: разделить капитал по назначению','Выдели деньги на жизнь и резерв, на цели ближайших лет и на долгосрочный рост. Не держи всё в одном банке, одной квартире, одной компании или одном бизнесе. Для вкладов проверь действующие лимиты страхования; для облигаций — надёжность эмитента и срок; для акций — риск падения цены; для недвижимости — расходы и время продажи. Если открываешь бизнес, заранее установи максимальную сумму, которую готов потерять.'],
 ['Более 20 миллионов: защитить разные источники богатства','Проверь, какая доля капитала приходится на жильё, бизнес, депозиты, облигации и акции, и насколько быстро каждый актив можно продать. Снизь зависимость от одного банка, арендатора, клиента или предприятия. С бухгалтером оцени налоги на проценты, инвестиционный доход, аренду и бизнес. С юристом проверь, на кого оформлены активы, какие долги или обязательства с ними связаны, и как семья сможет получить доступ к имуществу при наследовании.']
 ];
 const [title,detail]=variants[tier];
 const plan=['Посчитай, сколько денег должно оставаться доступным на ближайшие 3–6 месяцев расходов.','Раздели оставшуюся сумму по срокам: до года, 1–3 года и дольше трёх лет.','Для каждого варианта запиши возможный убыток, срок возврата денег и расходы на обслуживание.','Прежде чем вкладывать в дело, проверь спрос на небольшом тесте и установи лимит потерь.'];
 return {priority:60,title:'Возможности твоего капитала',short:`Доступные накопления: ${money(cash)}. ${title}.`,detail,why:'Одинаковая сумма может служить резервом, деньгами на покупку или капиталом для роста. Выбор зависит от сроков и готовности к риску.',steps:plan,impact:`Ориентир на три месяца необходимых расходов: ${money(base)}. Сверх него доступно около ${money(available)} — только если все накопления действительно свободны от ближайших обязательств. Прочие активы: ${money(other)}; их нельзя считать деньгами на счёте. ${free>0?`Положительный остаток ${money(free)} в месяц можно распределять между целями.`:''}`,learn:'Что изучить: страхование вкладов, доходность после налогов и комиссий, кредитный риск облигаций, ликвидность недвижимости, расчёт прибыли малого бизнеса.',group:'opportunity'};
}
function incomeOpportunity(d){
 const free=d.free;
 return {priority:57,title:'Как использовать ежемесячный остаток',short:`После расходов остаётся ${money(free)} в месяц. Выбери конкретное назначение этим деньгам.`,detail:'Необязательно сразу инвестировать весь остаток. Для близкой покупки подойдут доступные и менее рискованные способы хранения; для долгого срока можно изучать фонды, акции и облигации. Для повышения дохода рассмотрите обучение прикладному навыку или небольшой тест услуги с понятной себестоимостью.',why:'Если у свободных денег нет назначения, они незаметно уходят на покупки и не приближают цели.',steps:['Выдели ближайшую цель и её стоимость.','Определи сумму, которую готов направлять на неё ежемесячно.','Для долгосрочной части сравни несколько инструментов по риску и сроку.','Если интересен бизнес, начни с проверки спроса и первого клиента.'],impact:`Пример распределения ${money(free)}: ${money(free*.5)} на цели и резерв, ${money(free*.3)} на долгосрочные накопления, ${money(free*.2)} на обучение или тест идеи. Это иллюстрация, а не обязательная пропорция; при долгах или слабом резерве приоритеты другие.`,learn:'Что изучить: постановка финансовой цели, разница между вкладом, облигацией и акцией, тестирование бизнес-идеи.',group:'opportunity'};
}
function profile(d){
 const issues=[];
 const cash=values.cash||0;
 const hasIncome=d.income>0,hasCosts=d.essentials>0;
 const push=(severity,title,description,anchor,detail)=>issues.push({severity,title,description,anchor,detail});
 if(!hasIncome)push(95,'Доход не указан','Невозможно оценить долю свободных денег и кредитную нагрузку.','Доход: 0 ₽','Проверь, действительно ли сейчас нет поступлений или поле осталось пустым.');
 if(d.free<0)push(100,'Ежемесячный дефицит','Расходы и платежи превышают поступления.',`Разрыв: ${money(-d.free)} в месяц`,'Это главный риск для устойчивости: отрицательный денежный поток постепенно уменьшает доступный резерв.');
 else if(hasIncome&&d.free===0)push(82,'Нет свободного остатка','После текущих расходов и платежей ничего не остаётся.','Свободный остаток: 0 ₽','Даже небольшой непредвиденный платёж может потребовать использования накоплений.');
 else if(hasIncome&&d.free/d.income<.1)push(52,'Небольшой запас в денежном потоке','Свободный остаток меньше 10% поступлений.',`Остаток: ${money(d.free)} (${Math.round(d.free/d.income*100)}%)`,'Финансовая гибкость ограничена даже при положительном балансе.');
 if(hasIncome&&d.load>=.5)push(96,'Критичная доля долговых платежей','На платежи уходит половина дохода или больше.',`Нагрузка: ${Math.round(d.load*100)}% · ${money(d.payments)}/мес.`,'Высокая фиксированная нагрузка повышает чувствительность к снижению дохода.');
 else if(hasIncome&&d.load>=.3)push(74,'Повышенная долговая нагрузка','Платежи занимают значительную часть поступлений.',`Нагрузка: ${Math.round(d.load*100)}% · ${money(d.payments)}/мес.`,'Сравни нагрузку с оставшимися обязательными расходами и запасом доступных денег.');
 if(hasCosts&&d.buffer<1)push(90,'Резерв меньше одного месяца','Доступных накоплений не хватит на месяц необходимых расходов.',`Резерв: ${d.buffer.toFixed(1)} мес. · до 1 мес. ${money(Math.max(0,d.essentials-cash))}`,'Недостаток ликвидного резерва особенно важен при нестабильных поступлениях.');
 else if(hasCosts&&d.buffer<3)push(65,'Резерв ниже базового ориентира','Подушка покрывает меньше трёх месяцев необходимых расходов.',`Резерв: ${d.buffer.toFixed(1)} мес. · до 3 мес. ${money(Math.max(0,3*d.essentials-cash))}`,'Ориентир 3–6 месяцев не универсален; для нестабильного дохода может понадобиться больше.');
 else if(!hasCosts)push(46,'Резерв невозможно оценить','Обязательные расходы равны нулю или не заполнены.','Месячная база: 0 ₽','Без необходимых расходов нельзя корректно рассчитать срок покрытия резервом.');
 if(d.net<0)push(68,'Отрицательный чистый капитал','Остаток долгов выше оценочной стоимости активов.',`Разница: ${money(-d.net)}`,'Стоимость имущества приблизительна; особенно важно не путать неликвидные активы с доступными деньгами.');
 if(d.payments>0&&d.debt===0)push(88,'Проверь остаток долга','Платежи есть, но остаток долга указан нулевым.',`Платежи: ${money(d.payments)}/мес.`,'Уточнение остатка может существенно изменить оценку чистого капитала.');
 if(d.debt>0&&d.payments===0)push(44,'Проверь график выплат','Долг указан, но ежемесячный платёж отсутствует.',`Долг: ${money(d.debt)}`,'Если выплаты отложены или долг беспроцентный, текущая нагрузка может быть нулевой — но обязательство остаётся.');
 if(d.income>0&&d.monthly>d.income*1.5)push(60,'Проверь период расходов','Траты и платежи превышают доход более чем в полтора раза.',`Расходы: ${money(d.monthly)} · доход: ${money(d.income)}`,'Проверь, не учтены ли кредитные платежи дважды или разовые расходы как ежемесячные.');
 if(d.income>0&&d.free>0&&d.free/d.income>=.25&&d.buffer!==null&&d.buffer<3)push(50,'Хороший поток, но слабый резерв','Существенный свободный остаток пока не подкреплён доступной подушкой.',`Остаток: ${money(d.free)}/мес. · резерв: ${d.buffer.toFixed(1)} мес.`,'Текущие доходы и накопленная устойчивость — разные показатели.');
 if(d.assets>0&&cash/d.assets<.1&&hasCosts&&d.buffer<3)push(58,'Капитал есть, ликвидности мало','Большая часть активов не является доступными накоплениями.',`Активы: ${money(d.assets)} · доступно: ${money(cash)}`,'Недвижимость и прочие активы могут быть ценными, но не всегда помогают срочно оплачивать расходы.');
 issues.sort((a,b)=>b.severity-a.severity);
 let name='Сбалансированная финансовая база',summary='По введённым данным явных критических перекосов не обнаружено. Следи за динамикой показателей, а не только за оценкой в один день.';
 if(!hasIncome&&d.monthly>0){name='Нет подтверждённого дохода';summary=`Указаны расходы ${money(d.monthly)} в месяц при нулевых поступлениях. Оценка устойчивости ограничена: сначала проверь исходные данные.`}
 else if(d.free<0){name='Денежный поток в дефиците';summary=`Расходы превышают доход на ${money(-d.free)} ежемесячно. Это основной фактор риска независимо от стоимости имущества.`}
 else if(hasIncome&&d.load>=.5){name='Высокая долговая зависимость';summary=`Долговые платежи забирают ${Math.round(d.load*100)}% дохода. Даже положительный баланс может быть уязвим при снижении поступлений.`}
 else if(hasCosts&&d.buffer<1){name='Недостаточный запас прочности';summary=`Доступного резерва хватает на ${d.buffer.toFixed(1)} месяца необходимых расходов. Текущие активы не заменяют ликвидную подушку.`}
 else if(d.assets>=2000000&&hasCosts&&d.buffer<3){name='Капитал с ограниченной ликвидностью';summary=`Общие активы составляют ${money(d.assets)}, но доступный резерв покрывает только ${d.buffer.toFixed(1)} месяца обязательных расходов.`}
 else if(hasIncome&&d.free/d.income>=.2&&hasCosts&&d.buffer>=3){name='Основа для накопления капитала';summary=`Свободный остаток ${money(d.free)} в месяц и резерв ${d.buffer.toFixed(1)} месяца создают запас гибкости. Это не гарантия стабильности будущих доходов.`}
 else if(hasIncome&&d.free/d.income<.1){name='Ограниченная финансовая гибкость';summary=`Свободный остаток составляет ${money(d.free)} в месяц. Даже при положительном балансе запас для неожиданных расходов небольшой.`}
 else if(!hasCosts){name='Недостаточно данных о расходах';summary='Обязательные расходы не указаны: резерв и устойчивость нельзя интерпретировать полноценно.'}
 const primary=issues[0]||null;
 return {name,summary,primary,issues:issues.slice(0,3),complete:hasIncome&&hasCosts};
}

function renderProfile(d){
 const p=profile(d),root=$('profile');root.replaceChildren();
 const heading=document.createElement('div');heading.className='profile-heading';
 const eyebrow=document.createElement('span');eyebrow.className='eyebrow';eyebrow.textContent='Персональный финансовый профиль';
 const title=document.createElement('h3');title.textContent=p.name;
 const intro=document.createElement('p');intro.textContent=p.summary;
 heading.append(eyebrow,title,intro);root.append(heading);
 const section=document.createElement('div');section.className='profile-priorities';
 const sub=document.createElement('h4');sub.textContent=p.issues.length?'На что обратить внимание в первую очередь':'Критических сигналов по введённым данным нет';section.append(sub);
 p.issues.forEach((issue,i)=>{const card=document.createElement('div');card.className='profile-issue'+(i===0?' primary':'');const rank=document.createElement('span');rank.className='profile-rank';rank.textContent=i===0?'Главный вывод':`Приоритет ${i+1}`;const h=document.createElement('b');h.textContent=issue.title;const a=document.createElement('strong');a.textContent=issue.anchor;const p=document.createElement('p');p.textContent=issue.description+' '+issue.detail;card.append(rank,h,a,p);section.append(card)});
 root.append(section);
 const foot=document.createElement('p');foot.className='profile-foot';foot.textContent='Это диагностические сигналы, а не индивидуальная инвестиционная, кредитная или юридическая рекомендация. Ориентир резерва 3–6 месяцев зависит от ситуации.';root.append(foot);
}

function guidance(d){
 const p=profile(d);
 return {items:p.issues.map((x,i)=>({title:x.title,short:x.anchor,detail:x.description+' '+x.detail,why:i===0?'Это наиболее значимый диагностический сигнал по введённым данным.':'Дополнительный фактор, влияющий на финансовую устойчивость.',impact:x.anchor,steps:[],learn:'Проверь точность исходных сумм и сравни показатель с предыдущим месяцем.'})),warnings:[]};
}

function renderGuidance(d){
 const {items}=guidance(d),a=$('actions');a.replaceChildren();
 if(!items.length){a.append(block('Серьёзных перекосов не обнаружено','Периодически обновляй показатели, особенно при изменении дохода, долгов или обязательных расходов.'));return}
 items.forEach((item,i)=>{const el=block((i===0?'Главный сигнал: ':'')+item.title,item.detail);el.classList.add('advice-card');a.append(el)});
}

function results(scroll=true){let d=data();if(d.income===0&&d.monthly===0&&d.assets===0&&d.debt===0){$('error').textContent='Для диагностики введи хотя бы один показатель.';return}const score=calculateScore(d);$('scoreRing').dataset.tone=score===null?'neutral':score<45?'danger':score<75?'warn':'good';$('scoreRing').style.setProperty('--pct',(score===null?0:score)+'%');$('scoreValue').textContent=score===null?'—':score;$('scoreRing').setAttribute('aria-label',score===null?'Индекс не рассчитан: недостаточно данных':'Индекс финансовой устойчивости: '+score+' из 100');$('scoreLabel').textContent=score===null?'Недостаточно данных':score>=75?'Хороший запас устойчивости':score>=45?'Есть точки для улучшения':'Требуется внимание';const items=[
 ['Месячный баланс',money(d.free),'Доходы минус расходы и платежи',d.income>0?clamp(d.free/d.income*100,0,100):0,d.free<0?'danger':d.free===0?'warn':'good'],
 ['Доля свободных денег',d.income?Math.round(d.free/d.income*100)+' %':'Нет дохода','От дохода после всех платежей',d.income?clamp(d.free/d.income*100,0,100):0,d.free<=0?'danger':d.free/d.income<.1?'warn':'good'],
 ['Кредитная нагрузка',d.income?Math.round(d.payments/d.income*100)+' %':'Нет дохода','Платежи по долгам / доход',d.income?clamp(d.payments/d.income/.5*100,0,100):0,d.income===0?'neutral':d.load>=.5?'danger':d.load>=.3?'warn':'good'],
 ['Резерв',d.buffer===null?'Нет базы':d.buffer.toFixed(1)+' мес.','Покрытие обязательных расходов',d.buffer===null?0:clamp(d.buffer/6*100,0,100),d.buffer===null?'neutral':d.buffer<1?'danger':d.buffer<3?'warn':'good'],
 ['Чистый капитал',money(d.net),'Все активы минус долги',null,d.net<0?'danger':'good'],
 ['Обязательные расходы',money(d.essentials),'Без досуга и необязательных покупок',null,'neutral']
 ];
 $('metrics').replaceChildren(...items.map(([a,b,c,pct,tone],i)=>{let el=document.createElement('div');el.className='panel metric tone-'+tone;let small=document.createElement('small');small.textContent=a;let strong=document.createElement('strong');strong.textContent=b;let sub=document.createElement('span');sub.textContent=c;el.append(small,strong,sub);if(pct!==null){const track=document.createElement('div');track.className='metric-track';track.setAttribute('role','img');track.setAttribute('aria-label',a+': '+b);const fill=document.createElement('div');fill.className='metric-fill';fill.style.width=pct+'%';track.append(fill);el.append(track)}return el}));const f=$('findings'),a=$('actions');f.replaceChildren();a.replaceChildren();if(d.income===0)add(f,'Доход не указан','Процентные показатели и оценка кредитной нагрузки нельзя интерпретировать без дохода.');if(d.free<0)add(f,'Отрицательный баланс',`Ежемесячно не хватает около ${money(-d.free)}. Этот разрыв опасно регулярно покрывать новыми долгами.`);else if(d.free===0)add(f,'Баланс на границе','После расходов не остаётся свободных денег. Любая непредвиденная трата может потребовать заимствования.');else add(f,'Положительный денежный поток',`После расходов остаётся около ${money(d.free)} в месяц — возможный ресурс для резерва или ускоренного погашения долгов.`);if(d.income>0){if(d.load>=.5)add(f,'Высокая долговая нагрузка','На платежи уходит не менее половины дохода. Это серьёзно уменьшает финансовую гибкость.');else if(d.load>=.3)add(f,'Заметная долговая нагрузка','Платежи занимают 30–50% дохода. Важно проверить условия долгов и запас прочности.');else add(f,'Платежи по долгам',`Их доля — ${Math.round(d.load*100)}% дохода. Оценивать риск нужно также с учётом нестабильности заработка.`)}if(d.buffer===null)add(f,'Резерв пока не оценён','Для оценки подушки нужно указать обязательные расходы.');else if(d.buffer<1)add(f,'Маленький резерв','Доступные накопления покрывают меньше одного месяца обязательных расходов.');else if(d.buffer<3)add(f,'Резерв требует укрепления','Накоплений хватает примерно на 1–3 месяца обязательных расходов.');else add(f,'Финансовая подушка',`Доступные средства покрывают примерно ${d.buffer.toFixed(1)} месяца обязательных расходов.`);add(f,'Чистый капитал',d.net>=0?'Оценочная стоимость активов выше текущего остатка долгов.':'Остаток долгов больше оценочной стоимости активов. Следи за снижением задолженности и стоимостью залогового имущества.');
renderProfile(d);renderGuidance(d);$('results').classList.add('show');if(scroll)$('results').scrollIntoView({behavior:'smooth',block:'start'})}
$('edit').onclick=()=>document.querySelector('.layout').scrollIntoView({behavior:'smooth'});$('quickEdit').addEventListener('click',e=>{const btn=e.target.closest('[data-edit-step]');if(!btn)return;cancelPendingReport();step=Number(btn.dataset.editStep);render();document.querySelector('.layout').scrollIntoView({behavior:'smooth',block:'start'});});$('reset').onclick=()=>{if(confirm('Начать новую диагностику и очистить введённые суммы?')){cancelPendingReport();allFields.forEach(k=>values[k]=0);step=0;render();$('results').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})}};let printExpanded=[];window.addEventListener('beforeprint',()=>{printExpanded=[...document.querySelectorAll('details.advice-detail:not([open])')];printExpanded.forEach(el=>el.open=true)});window.addEventListener('afterprint',()=>{printExpanded.forEach(el=>el.open=false);printExpanded=[]});render();
