'use strict';
const cfg=[{name:'Доходы',title:'Сколько денег приходит?',intro:'Укажи средние суммы за месяц. Если доход нерегулярный, лучше взять осторожную оценку за последние несколько месяцев.',fields:[['salary','Зарплата и постоянный доход'],['extra','Подработка и другие доходы']]},{name:'Расходы',title:'Куда уходят деньги?',intro:'Введи среднемесячные траты без кредитных платежей — их учтём отдельно. Не забудь про нерегулярные расходы, пересчитанные на месяц.',fields:[['housing','Жильё и коммунальные услуги'],['food','Продукты и питание'],['transport','Транспорт'],['family','Семья, здоровье и обязательные траты'],['other','Досуг, покупки и прочее']]},{name:'Долги',title:'Какие есть обязательства?',intro:'Для расчёта нагрузки нужны ежемесячные платежи. Общий остаток долга используется при расчёте чистого капитала.',fields:[['payments','Общие ежемесячные платежи по долгам'],['debt','Остаток всех долгов и кредитов']]},{name:'Капитал',title:'Что уже накоплено?',intro:'Включай доступные денежные резервы и примерную рыночную стоимость других активов. Не учитывай одно и то же дважды.',fields:[['cash','Доступные накопления и резерв'],['assets','Стоимость остальных активов (жильё, инвестиции и другое)']]}];
const fieldHints={salary:'После налогов, сумма на руки.',extra:'Средний доход от подработок за месяц, за вычетом связанных расходов.',housing:'Аренда, коммунальные услуги и содержание жилья — без платежей по ипотеке.',food:'Продукты, кафе и питание за месяц.',transport:'Проезд, топливо, обслуживание транспорта.',family:'Лечение, дети, обязательные покупки и другие необходимые траты.',other:'Необязательные покупки, развлечения и подписки.',payments:'Сумма платежей по ипотеке, кредитам, рассрочкам и займам за месяц.',debt:'Сколько всего осталось вернуть кредиторам, а не первоначальная сумма кредитов.',cash:'Деньги на счетах, вкладах и наличные, которыми реально можно воспользоваться.',assets:'Примерная стоимость жилья, автомобиля, инвестиций и другого имущества. Не дублируй деньги из предыдущего поля.'};const values={};const allFields=cfg.flatMap(s=>s.fields.map(x=>x[0]));allFields.forEach(k=>values[k]=0);let step=0;const $=id=>document.getElementById(id);const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));const sum=keys=>keys.reduce((v,k)=>v+(values[k]||0),0);const data=()=>{let income=sum(['salary','extra']),expenses=sum(['housing','food','transport','family','other']),payments=values.payments||0,monthly=expenses+payments,free=income-monthly,essentials=sum(['housing','food','transport','family'])+payments,assets=sum(['cash','assets']),debt=values.debt||0;return {income,expenses,payments,monthly,free,essentials,assets,debt,net:assets-debt,buffer:essentials>0?values.cash/essentials:null,load:income>0?payments/income:null,savings:income>0?free/income:null}};
function render(){const s=cfg[step];$('stepText').textContent=`Этап ${step+1} из 4`;$('tabs').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===step);b.setAttribute('aria-current',i===step?'step':'false')});let fields=s.fields.map(([key,label])=>`<div class="field"><label for="f-${key}">${label}</label><span class="field-hint">${fieldHints[key]||''}</span><div class="inputwrap"><input type="number" id="f-${key}" data-key="${key}" min="0" max="1000000000000" step="100" inputmode="decimal" value="${values[key]||''}" placeholder="0" aria-label="${label}"><span class="rub">₽</span></div></div>`).join('');$('stage').innerHTML=`<div class="section"><h3>${s.title}</h3><p>${s.intro}</p><div class="fields">${fields}</div><div class="note">${step===2?'Если долгов нет, оставь поля пустыми. Платежи уже не должны входить в раздел обычных расходов.':step===3?'Важно: стоимость квартиры и других активов не равна свободным деньгам. Для рекомендаций о доступных накоплениях используется отдельное поле «Доступные накопления».':'Не нужно вводить точные личные данные — достаточно приблизительных сумм.'}</div></div>`;$('stage').querySelectorAll('input').forEach(el=>el.addEventListener('input',()=>{const n=el.value===''?0:Number(el.value);if(Number.isFinite(n)&&n>=0&&n<=1e12){values[el.dataset.key]=n;$('error').textContent='';preview();if($('results').classList.contains('show'))results(false)}}));$('prev').disabled=step===0;$('next').textContent=step===3?'Получить результаты →':'Далее →';preview()}
function preview(){const d=data();$('incomePreview').textContent=money(d.income);$('outPreview').textContent=money(d.monthly);$('freePreview').textContent=money(d.free);$('freePreview').className=d.free<0?'red':'green';$('progress').style.width=((step+1)/4*100)+'%'}
function validate(){for(const [k] of cfg[step].fields){let el=$('f-'+k);if(!el)continue;const n=el.value===''?0:Number(el.value);if(!Number.isFinite(n)||n<0||n>1e12){$('error').textContent='Проверь суммы: допустимы только неотрицательные числа до 1 трлн рублей.';el.focus();return false}}return true}
$('prev').onclick=()=>{if(step>0){step--;render()}};$('next').onclick=()=>{if(!validate())return;if(step<3){step++;render()}else results()};$('tabs').addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t&&validate()){step=Number(t.dataset.tab);render()}});
function calculateScore(d){let score=0;let checks=0;if(d.income>0){score+=clamp(d.free/d.income,0,0.25)/0.25*30;score+=clamp(1-(d.payments/d.income)/0.5,0,1)*20;checks+=2}if(d.essentials>0){score+=clamp(d.buffer||0,0,6)/6*30;checks++}score+=(d.net>=0?20:clamp(1+d.net/Math.max(d.debt,1),0,1)*20);checks++;return clamp(Math.round(score),0,100)}
function block(title,text){const e=document.createElement('div');e.className='finding';const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=text;e.append(b,p);return e}function add(parent,title,txt){parent.append(block(title,txt))}
function capitalAdvice(d){
 const cash=values.cash||0,other=values.assets||0,free=d.free,base=d.essentials>0?d.essentials*3:0,available=Math.max(0,cash-base);
 const tier=cash<500000?0:cash<2000000?1:cash<5000000?2:cash<20000000?3:4;
 const variants=[
 ['Небольшие суммы: создать запас и проверить идею','Начни с доступного резерва. Если он уже есть, сравни вклад и короткие надёжные облигации с учётом срока и риска. Для малого дела проверь спрос на услугу: ремонт, обучение, дизайн, прокат вещей или помощь бизнесу. Сначала найди потенциальных клиентов и рассчитай расходы, а не покупай оборудование вслепую.'],
 ['От 500 тысяч до 2 миллионов: разделить деньги по задачам','Часть оставь на непредвиденные расходы и ближайшие покупки — на доступном счёте или вкладе. Для денег, которые не понадобятся в ближайшее время, изучи облигации: кто их выпустил, когда вернёт долг и может ли не заплатить. На предпринимательский эксперимент выделяй только ограниченную сумму, потеря которой не нарушит семейный бюджет.'],
 ['От 2 до 5 миллионов: сравнить несколько путей','Первый путь — вклады и качественные облигации с разными сроками погашения, чтобы не зависеть от одной даты. Второй — часть долгосрочных денег вложить в диверсифицированные фонды или акции, понимая, что стоимость может сильно падать. Третий — проверить собственный небольшой бизнес с бюджетом и ограничением убытка. Недвижимость сравнивай по чистому доходу от аренды после ремонта, налогов и простоя, а не только по цене объявления.'],
 ['От 5 до 20 миллионов: разделить капитал по назначению','Выдели деньги на жизнь и резерв, на цели ближайших лет и на долгосрочный рост. Не держи всё в одном банке, одной квартире, одной компании или одном бизнесе. Для вкладов проверь действующие лимиты страхования; для облигаций — надёжность эмитента и срок; для акций — риск падения цены; для недвижимости — расходы и время продажи. Если открываешь бизнес, заранее установи максимальную сумму, которую готов потерять.'],
 ['Более 20 миллионов: защитить разные источники богатства','Проверь, какая доля капитала приходится на жильё, бизнес, депозиты, облигации и акции, и насколько быстро каждый актив можно продать. Снизь зависимость от одного банка, арендатора, клиента или предприятия. С бухгалтером оцени налоги на проценты, инвестиционный доход, аренду и бизнес. С юристом проверь, на кого оформлены активы, какие долги или обязательства с ними связаны, и как семья сможет получить доступ к имуществу при наследовании.']
 ];
 const [title,detail]=variants[tier];
 const plan=['Посчитай, сколько денег должно оставаться доступным на ближайшие 3–6 месяцев расходов.','Раздели оставшуюся сумму по срокам: до года, 1–3 года и дольше трёх лет.','Для каждого варианта запиши возможный убыток, срок возврата денег и расходы на обслуживание.','Прежде чем вкладывать в дело, проверь спрос на небольшом тесте и установи лимит потерь.'];
 return {priority:60,title:'Возможности твоего капитала',short:`Доступные накопления: ${money(cash)}. ${title}.`,detail,why:'Одинаковая сумма может служить резервом, деньгами на покупку или капиталом для роста. Выбор зависит от сроков и готовности к риску.',steps:plan,impact:`Ориентир на три месяца необходимых расходов: ${money(base)}. Сверх него доступно около ${money(available)} — только если все накопления действительно свободны от ближайших обязательств. Прочие активы: ${money(other)}; их нельзя считать деньгами на счёте. ${free>0?`Положительный остаток ${money(free)} в месяц можно распределять между целями.`:''}`,learn:'Что изучить: страхование вкладов, доходность после налогов и комиссий, кредитный риск облигаций, ликвидность недвижимости, расчёт прибыли малого бизнеса.',group:'opportunity'};
}
function incomeOpportunity(d){
 const free=d.free;
 return {priority:57,title:'Как использовать ежемесячный остаток',short:`После расходов остаётся ${money(free)} в месяц. Выбери конкретное назначение этим деньгам.`,detail:'Необязательно сразу инвестировать весь остаток. Для близкой покупки подойдут доступные и менее рискованные способы хранения; для долгого срока можно изучать фонды, акции и облигации. Для повышения дохода рассмотрите обучение прикладному навыку или небольшой тест услуги с понятной себестоимостью.',why:'Если у свободных денег нет назначения, они незаметно уходят на покупки и не приближают цели.',steps:['Выдели ближайшую цель и её стоимость.','Определи сумму, которую готов направлять на неё ежемесячно.','Для долгосрочной части сравни несколько инструментов по риску и сроку.','Если интересен бизнес, начни с проверки спроса и первого клиента.'],impact:`Пример распределения ${money(free)}: ${money(free*.5)} на цели и резерв, ${money(free*.3)} на долгосрочные накопления, ${money(free*.2)} на обучение или тест идеи. Это иллюстрация, а не обязательная пропорция; при долгах или слабом резерве приоритеты другие.`,learn:'Что изучить: постановка финансовой цели, разница между вкладом, облигацией и акцией, тестирование бизнес-идеи.',group:'opportunity'};
}
function guidance(d){
 const items=[],warnings=[];
 const put=(priority,title,short,detail)=>items.push({priority,title,short,detail});
 if(d.income===0)warnings.push('Доход не указан: доли расходов и кредитная нагрузка не рассчитываются.');
 if(d.debt===0&&d.payments>0)warnings.push('Есть ежемесячные платежи по долгам, но остаток долга равен нулю. Уточни данные.');
 if(d.debt>0&&d.payments===0)warnings.push('Указан долг, но нет платежей. Возможно, долг без ежемесячных выплат — проверь условия.');
 if(d.income>0&&d.monthly>d.income*1.5)warnings.push('Расходы значительно превышают доходы. Проверь период и не учтены ли кредитные платежи дважды.');
 if(d.essentials===0&&d.income>0)warnings.push('Обязательные расходы не указаны: оценка резервной подушки может быть неполной.');
 if(d.free<0)put(100,'Выйти из ежемесячного минуса',`Сейчас не хватает ${money(-d.free)} в месяц. Сначала останови рост дефицита.`,`Проверь основные расходы за последние 30 дней и найди сочетание сокращения затрат и дополнительного заработка минимум на ${money(-d.free)} ежемесячно. Если доход нестабилен, используй осторожную оценку. Не перекрывай постоянный минус новыми дорогими кредитами.`);
 if(d.income===0&&d.monthly>0)put(98,'Найти источник поступлений',`Для покрытия текущих расходов нужно не менее ${money(d.monthly)} в месяц.`, 'Оцени регулярные источники дохода и навыки, которые можно монетизировать. Для начала проверь небольшие подработки без вложений: услуги, помощь клиентам, временная работа. Не бери новые обязательства ради непроверенного заработка.');
 if(d.income>0&&d.load>=.3)put(d.load>=.5?95:78,'Пересмотреть кредитную нагрузку',`Платежи составляют ${Math.round(d.load*100)}% дохода (${money(d.payments)} ежемесячно).`, 'Выпиши каждый долг: остаток, ставку, обязательный платёж и срок. В первую очередь предотвращай просрочки. Проверь возможность снизить ставку или нагрузку, но сравни полную стоимость нового договора и дополнительные комиссии. Для досрочных платежей сначала сохрани деньги на обязательные расходы.');
 if(d.buffer!==null&&d.buffer<1)put(88,'Сформировать первый резерв',`До подушки на 1 месяц не хватает ${money(Math.max(0,d.essentials-values.cash))}.`,`Первый ориентир — ${money(d.essentials)} доступных денег. Храни их отдельно от повседневных трат, с возможностью быстро снять без существенных потерь. При дефиците бюджета сначала восстанови баланс, затем постепенно пополняй запас.`);
 else if(d.buffer!==null&&d.buffer<3)put(70,'Укрепить финансовую подушку',`До запаса на 3 месяца не хватает ${money(Math.max(0,d.essentials*3-values.cash))}.`,`При нынешних обязательных расходах ориентир на три месяца — ${money(d.essentials*3)}. Если свободных денег достаточно, начни с посильного регулярного перевода после зарплаты. При нестабильном доходе, иждивенцах и рисках работы может потребоваться больший резерв.`);
 if(false&&d.free>0&&d.buffer!==null&&d.buffer<3){
 const transfer=Math.min(Math.round(d.free*.3/100)*100,Math.max(0,d.essentials*3-values.cash));
 if(transfer>0)put(58,'Запланировать пополнение накоплений',`Можно рассмотреть перевод около ${money(transfer)} в месяц из свободного остатка ${money(d.free)}.`, 'Это пример осторожного сценария — не автоматическое обязательство. Проверь, нет ли сезонных расходов и просрочек. Установи посильную сумму, которую реально сохранять ежемесячно, и пересматривай её после изменения дохода.');
 }
 if(d.free>=0&&d.debt>0&&!(d.load>=.3))put(48,'Сравнить стратегии погашения долгов','Проверь, какие долги дороже всего по процентам.','При наличии нескольких кредитов сравни метод «лавины» (сначала максимальная ставка) и «снежного кома» (сначала минимальный остаток). Учитывай страховки, комиссии, условия досрочного погашения и резерв на непредвиденные расходы.');
 if(false&&d.free>0&&d.buffer!==null&&d.buffer>=3)put(42,'Назначить цель свободным деньгам',`После расходов остаётся ${money(d.free)} в месяц.`, 'Раздели цели по срокам. Деньги для ближайших покупок лучше не подвергать значительным рыночным рискам. Для долгосрочных целей сначала изучи диверсификацию, комиссии, налоги и возможные просадки, затем выбери подходящие инструменты.');
 if(d.net<0)put(55,'Контролировать чистый капитал',`Долги превышают активы на ${money(-d.net)}.`, 'Проверь, не завышена ли стоимость активов и все ли долги учтены. Отслеживай изменение чистого капитала раз в месяц: снижение долгов и рост резерва важнее красивой оценки имущества.');
 if(!items.length)put(20,'Продолжать финансовый контроль','Раз в месяц обновляй данные и проверяй изменения.','Следи за фактическими расходами, сохрани доступный резерв и выбирай финансовые цели с учётом срока и риска. Повторяй диагностику после заметных изменений дохода или обязательств.');
 if(d.free>0)items.push(incomeOpportunity(d));if(values.cash>0||values.assets>0)items.push(capitalAdvice(d));items.sort((a,b)=>b.priority-a.priority);
 const core=items.filter(x=>!x.group);const opportunities=items.filter(x=>x.group);const selected=[...core.slice(0,d.free<0?2:1),...opportunities.slice(0,2)];if(selected.length<3)selected.push(...core.filter(x=>!selected.includes(x)).slice(0,3-selected.length));const enriched=selected.slice(0,3).map(item=>{if(item.group)return item;
 let why='',steps=[],impact='',learn='';
 if(item.title.includes('минуса')){why='Регулярный дефицит постепенно съедает накопления и повышает риск новых долгов.';steps=['Проверь расходы по выпискам за последние 30 дней.','Выдели обязательные траты и покупки, которые можно перенести.','Выбери один реальный способ дополнительного дохода без крупных вложений.','Раз в неделю сравни фактический баланс с планом.'];impact=`Чтобы выйти в ноль, нужно улучшить баланс на ${money(-d.free)} ежемесячно; для запаса в 10% дохода — на ${money(-d.free+Math.max(0,d.income*.1))}.`;learn='Темы: учёт денежных потоков, обязательные и переменные расходы, планирование нерегулярного дохода.'}
 else if(item.title.includes('кредитную')){why='Чем выше доля обязательных платежей, тем меньше возможностей пережить снижение дохода.';steps=['Запиши остаток, ставку, платёж и срок каждого долга.','Проверь риск просрочек и условия изменения графика платежей.','Сравни общую переплату по вариантам, а не только размер нового платежа.','Не расходуй весь резерв на досрочное погашение.'];impact=d.income>0?`Для нагрузки 30% при прежнем доходе платежи должны быть не выше ${money(d.income*.3)}; разница с текущими — ${money(Math.max(0,d.payments-d.income*.3))} в месяц. Это ориентир, не обещание изменения договора.`:'';learn='Темы: полная стоимость кредита, эффективная ставка, рефинансирование, досрочное погашение.'}
 else if(item.title.includes('резерв')||item.title.includes('подушку')||item.title.includes('накоплений')){why='Резерв помогает оплачивать необходимое при потере заработка или непредвиденных событиях без срочных займов.';steps=['Сначала обеспечь положительный ежемесячный баланс.','Отдели резерв от денег на повседневные покупки.','Настрой посильное регулярное пополнение.','Пересматривай сумму резерва после изменения обязательных расходов.'];const gap=Math.max(0,d.essentials*3-values.cash),monthly=d.free>0?Math.min(d.free*.3,gap):0;impact=`Один месяц обязательных расходов — ${money(d.essentials)}, три месяца — ${money(d.essentials*3)}. ${monthly>0?`Если откладывать около ${money(monthly)} в месяц, до трёхмесячного резерва примерно ${Math.ceil(gap/monthly)} мес. без процентов.`:'Срок достижения цели пока не рассчитан: сначала нужен свободный денежный поток.'}`;learn='Темы: ликвидность, резерв на 3–6 месяцев, накопительный счёт и условия доступа к деньгам.'}
 else if(item.title.includes('доход')||item.title.includes('поступлений')){why='Без устойчивых поступлений даже небольшой обязательный расход быстро превращается в задолженность.';steps=['Оцени, сколько необходимо получать ежемесячно.','Составь список навыков и услуг, которые можешь предложить.','Проверь спрос на одну услугу без больших вложений.','Сравни чистый доход после расходов и налогов.'];impact=`Текущие ежемесячные обязательства и расходы — ${money(d.monthly)}; это минимальный ориентир поступлений для нулевого баланса.`;learn='Темы: доход от услуг, расчёт чистой прибыли, проверка спроса, финансовые риски подработки.'}
 else {why='Регулярное измерение финансовых показателей помогает принимать решения на основе цифр, а не ощущений.';steps=['Проверь точность доходов и расходов.','Определи ближайшую измеримую цель.','Назначь ежемесячную сумму на её достижение.','Повтори диагностику через месяц.'];impact=d.free>0?`Свободный денежный поток сейчас около ${money(d.free)} в месяц, или ${money(d.free*12)} за 12 месяцев при неизменных условиях.`:'Сначала проверь возможность создать устойчивый положительный остаток.';learn='Темы: финансовые цели, чистый капитал, планирование бюджета и управление рисками.'}
 return {...item,why,steps,impact,learn};
 });return {items:enriched,warnings};
}
function renderGuidance(d){
 const {items,warnings}=guidance(d),a=$('actions');a.replaceChildren();
 const addText=(parent,tag,text,cls)=>{const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;parent.append(el);return el};
 const groups=[{name:'Что улучшить',list:items.filter(x=>!x.group)},{name:'Какие есть возможности',list:items.filter(x=>x.group)}];
 groups.forEach(g=>{if(!g.list.length)return;const section=document.createElement('section');section.className='advice-group';addText(section,'h4',g.name,'group-title');g.list.forEach(item=>{
 const card=document.createElement('div');card.className='finding advice-card '+(item.group?'advice-opportunity':'advice-risk');addText(card,'b',item.title);addText(card,'p',item.short,'advice-short');
 const more=document.createElement('details');more.className='advice-detail';addText(more,'summary','Подробнее о рекомендации');
 const sectionText=(heading,value)=>{if(!value)return;const part=document.createElement('div');part.className='advice-part';addText(part,'h5',heading);addText(part,'p',value);if(heading==='Твои цифры и ориентиры')part.classList.add('advice-numbers');more.append(part)};
 sectionText('Почему это важно',item.why);sectionText('Что можно сделать',item.detail);
 if(item.steps&&item.steps.length){const part=document.createElement('div');part.className='advice-part';addText(part,'h5','Пошаговый план');const ol=document.createElement('ol');item.steps.forEach(t=>addText(ol,'li',t));part.append(ol);more.append(part)}
 sectionText('Твои цифры и ориентиры',item.impact);sectionText('Что изучить',item.learn);
 card.append(more);section.append(card);
 });a.append(section)});
 const f=$('findings');if(warnings.length){let heading=block('Проверь введённые данные',warnings.join(' '));heading.classList.add('input-warning');f.prepend(heading)}
}

function results(scroll=true){let d=data();if(d.income===0&&d.monthly===0&&d.assets===0&&d.debt===0){$('error').textContent='Для диагностики введи хотя бы один показатель.';return}const score=calculateScore(d);$('scoreRing').dataset.tone=score<45?'danger':score<75?'warn':'good';$('scoreRing').style.setProperty('--pct',score+'%');$('scoreValue').textContent=score;$('scoreLabel').textContent=score>=75?'Хороший запас устойчивости':score>=45?'Есть точки для улучшения':'Требуется внимание';const items=[
 ['Месячный баланс',money(d.free),'Доходы минус расходы и платежи',d.income>0?clamp(d.free/d.income*100,0,100):0,d.free<0?'danger':d.free===0?'warn':'good'],
 ['Доля свободных денег',d.income?Math.round(d.free/d.income*100)+' %':'Нет дохода','От дохода после всех платежей',d.income?clamp(d.free/d.income*100,0,100):0,d.free<=0?'danger':d.free/d.income<.1?'warn':'good'],
 ['Кредитная нагрузка',d.income?Math.round(d.payments/d.income*100)+' %':'Нет дохода','Платежи по долгам / доход',d.income?clamp(d.payments/d.income/.5*100,0,100):0,d.income===0?'neutral':d.load>=.5?'danger':d.load>=.3?'warn':'good'],
 ['Резерв',d.buffer===null?'Нет базы':d.buffer.toFixed(1)+' мес.','Покрытие обязательных расходов',d.buffer===null?0:clamp(d.buffer/6*100,0,100),d.buffer===null?'neutral':d.buffer<1?'danger':d.buffer<3?'warn':'good'],
 ['Чистый капитал',money(d.net),'Все активы минус долги',null,d.net<0?'danger':'good'],
 ['Обязательные расходы',money(d.essentials),'Без досуга и необязательных покупок',null,'neutral']
 ];
 $('metrics').replaceChildren(...items.map(([a,b,c,pct,tone],i)=>{let el=document.createElement('div');el.className='panel metric tone-'+tone;let small=document.createElement('small');small.textContent=a;let strong=document.createElement('strong');strong.textContent=b;let sub=document.createElement('span');sub.textContent=c;el.append(small,strong,sub);if(pct!==null){const track=document.createElement('div');track.className='metric-track';track.setAttribute('role','img');track.setAttribute('aria-label',a+': '+b);const fill=document.createElement('div');fill.className='metric-fill';fill.style.width=pct+'%';track.append(fill);el.append(track)}return el}));const f=$('findings'),a=$('actions');f.replaceChildren();a.replaceChildren();if(d.income===0)add(f,'Доход не указан','Процентные показатели и оценка кредитной нагрузки нельзя интерпретировать без дохода.');if(d.free<0)add(f,'Отрицательный баланс',`Ежемесячно не хватает около ${money(-d.free)}. Этот разрыв опасно регулярно покрывать новыми долгами.`);else if(d.free===0)add(f,'Баланс на границе','После расходов не остаётся свободных денег. Любая непредвиденная трата может потребовать заимствования.');else add(f,'Положительный денежный поток',`После расходов остаётся около ${money(d.free)} в месяц — возможный ресурс для резерва или ускоренного погашения долгов.`);if(d.income>0){if(d.load>=.5)add(f,'Высокая долговая нагрузка','На платежи уходит не менее половины дохода. Это серьёзно уменьшает финансовую гибкость.');else if(d.load>=.3)add(f,'Заметная долговая нагрузка','Платежи занимают 30–50% дохода. Важно проверить условия долгов и запас прочности.');else add(f,'Платежи по долгам',`Их доля — ${Math.round(d.load*100)}% дохода. Оценивать риск нужно также с учётом нестабильности заработка.`)}if(d.buffer===null)add(f,'Резерв пока не оценён','Для оценки подушки нужно указать обязательные расходы.');else if(d.buffer<1)add(f,'Маленький резерв','Доступные накопления покрывают меньше одного месяца обязательных расходов.');else if(d.buffer<3)add(f,'Резерв требует укрепления','Накоплений хватает примерно на 1–3 месяца обязательных расходов.');else add(f,'Финансовая подушка',`Доступные средства покрывают примерно ${d.buffer.toFixed(1)} месяца обязательных расходов.`);add(f,'Чистый капитал',d.net>=0?'Оценочная стоимость активов выше текущего остатка долгов.':'Остаток долгов больше оценочной стоимости активов. Следи за снижением задолженности и стоимостью залогового имущества.');
renderGuidance(d);$('results').classList.add('show');if(scroll)$('results').scrollIntoView({behavior:'smooth',block:'start'})}
$('edit').onclick=()=>document.querySelector('.layout').scrollIntoView({behavior:'smooth'});$('quickEdit').addEventListener('click',e=>{const btn=e.target.closest('[data-edit-step]');if(!btn)return;step=Number(btn.dataset.editStep);render();document.querySelector('.layout').scrollIntoView({behavior:'smooth',block:'start'});});$('reset').onclick=()=>{if(confirm('Начать новую диагностику и очистить введённые суммы?')){allFields.forEach(k=>values[k]=0);step=0;render();$('results').classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})}};let printExpanded=[];window.addEventListener('beforeprint',()=>{printExpanded=[...document.querySelectorAll('details.advice-detail:not([open])')];printExpanded.forEach(el=>el.open=true)});window.addEventListener('afterprint',()=>{printExpanded.forEach(el=>el.open=false);printExpanded=[]});render();
